### ISSUE TITLE
Data lost on restart

### ISSUE THREAD

**Issue by Yamakaky** [cozy-labs/cozy-docker#21]
When I restart the cozy container, all my data are lost. The [mongodb container](https://hub.docker.com/_/mongo/) page for example explains how to persist data. I couldn't find any similar explanation on https://hub.docker.com/r/cozy/full/.

**Comment by kosssi** [comment]
Hello @Yamakaky 

You can create a volume container with data. An example:

```
---

cozy_data:
  image: alpine
  volumes:
    - /etc/cozy
    - /var/lib/couchdb
    - /usr/local/cozy
  command: /bin/true

cozy:
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - cozy_data
```
